package common;

public enum TableStyle {
	GRIDVIEW,GANGTRIGGERFIELD,WORKFLOWTASKOWNERTRIGGERFIELD,
	COMBO,GANTCODETYPECOMBOBOX,materialName2,USERTRIGGERFIELD,
	BOMMGMT_LOCATOR,TREEVIEW,GANTGRIDCOMBOBOX,COLUMNFILTER;
}
